# Generated by Django 4.0.2 on 2022-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField(max_length=300, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('Orginal_price', models.TextField(null=True)),
                ('Discount_price', models.TextField(null=True)),
                ('Discountpercent', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='categorys',
        ),
        migrations.DeleteModel(
            name='Blog_category',
        ),
    ]
