# Generated by Django 4.0.2 on 2022-03-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0002_shop_remove_blogs_categorys_delete_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='query',
        ),
    ]
