# Generated by Django 4.0.2 on 2022-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0004_remove_team_date_remove_team_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50)),
                ('Time_of_day', models.CharField(max_length=50)),
                ('Way_to_reach', models.CharField(max_length=50)),
                ('time', models.TimeField(max_length=50)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Reason_for_appointment', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
