# Generated by Django 4.0.2 on 2022-04-14 18:51

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0009_remove_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rashi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('detail', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appionment',
            name='date',
        ),
        migrations.AddField(
            model_name='appionment',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
