# Generated by Django 4.0.2 on 2022-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0010_rashi_remove_appionment_date_appionment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rashi',
            name='date',
        ),
        migrations.AddField(
            model_name='rashi',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
