# Generated by Django 4.0.6 on 2022-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfitcoy', '0011_remove_rashi_date_rashi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
